//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoralTrend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class braceletInfo
    {
        public int braceletID { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public System.DateTime deedDate { get; set; }
        public string goodDeed { get; set; }
    }
}
